### ISSUE TITLE
Getting an error with the favicon

### ISSUE THREAD

**Issue by BenNewman90** [fac-15/FAC-YAK#27]
This is in my term{ [Error: ENOENT: no such file or directory, open '/Users/bennewman/FACN4/mentoring-week2/FAC-YAK/public/favi
con.ico']

The favicon isn't in the repo

**Comment by martinbagshaw** [comment]
I beg to differ:
![screen shot 2018-12-14 at 11 02 00](https://user-images.githubusercontent.com/28146666/49999835-bcef3680-ff8f-11e8-8f29-c38341da94a1.png)
